=== akhilkumargope/WSD_Lab_Assignment/Lab_Assignment_5/book_order.dtd
<!ELEMENT BookOrder (Customer, Order)>
<!ELEMENT Customer (Name, Email, Address)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Order (OrderDate, Item+)>
<!ELEMENT OrderDate (#PCDATA)>
<!ELEMENT Item (Title, Author, Price, RentalPeriod)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT RentalPeriod (#PCDATA)>
<!ATTLIST Customer id ID #REQUIRED>
<!ATTLIST Order id ID #REQUIRED>
<!ATTLIST Price currency CDATA #REQUIRED>

=== akhilkumargope/WSD_Lab_Assignment/Lab_Assignment_5/book_order_rental_lab5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BookOrder SYSTEM "book_order.dtd">
<BookOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="book_order.xsd">
    <Customer id="C001">
        <Name>Akhil Kumar Gope</Name>
        <Email>akhilkumar16.ak@gmail.com</Email>
        <Address>Kolkata</Address>
    </Customer>
    <Order id="O001">
        <OrderDate>2024-08-11</OrderDate>
        <Item>
            <Title>Deception Point</Title>
            <Author>Dann Brown</Author>
            <Price currency="INR">159.00</Price>
            <RentalPeriod>30</RentalPeriod>
        </Item>
    </Order>
</BookOrder>
